language: perl
perl:
  - "5.19"
  - "5.18"
  - "5.16"
  - "5.14"
# Whitelist branches for CI, ignore all other branches
branches:
  only:
    - master
env:
  - "HARNESS_OPTIONS=j9"
  - "cpanm -n --installdeps ."
  matrix:
    - TEST_AUTHOR=1
    - TEST_AUTHOR=0
    - fast_finish: true
notifications:
  email: false

